const RESPONSES = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};

const RESPONSE_STATUS = {
  SUCCESS: 200,
  ERROR: 400,
};
const RESPONSE_MESSAGES = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  ALREADY_ADDED: 'DATA ALREADY IMPORTED',
};

module.exports = {
  RESPONSES,
  RESPONSE_STATUS,
  RESPONSE_MESSAGES,
};
